name: ontrack
description: "Final Year Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  image_picker: ^1.0.5
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  mailer: ^6.0.1
  flutter_email_sender: ^5.0.1
  qr_flutter: ^4.1.0
  mongo_dart: ^0.9.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/icons/splashLogo.png
    - assets/icons/logoOnly.png
    - assets/icons/lostfound.png
    - assets/icons/trackroute.png
    - assets/icons/fee.png
    - assets/icons/edit.png
    - assets/icons/qrcode.png
    - assets/icons/routechange.png
    - assets/icons/report.png

  fonts:
    - family: FasterOne
      fonts:
        - asset: assets/fonts/FasterOne-Regular.ttf