name: ontrack
description: "Final Year Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  image_picker: ^1.0.5
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  mailer: ^6.0.1
  flutter_email_sender: ^5.0.1
  qr_flutter: ^4.1.0
  qr_code_scanner: 1.0.1
  mongo_dart: ^0.9.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  location: ^5.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.6.0
  http: ^0.13.0
  google_maps_webservice: ^0.0.19
  geolocator: ^11.0.0
  fluttertoast: ^8.2.4
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  image_gallery_saver: ^2.0.3
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/icons/timer.png
    - assets/icons/splashLogo.png
    - assets/icons/logoOnly.png
    - assets/icons/lostfound.png
    - assets/icons/trackroute.png
    - assets/icons/fee.png
    - assets/icons/edit.png
    - assets/icons/qrcode.png
    - assets/icons/report.png
    - assets/icons/buspin.png
    - assets/icons/pinloc.png
    - assets/icons/bus.png
    - assets/icons/language.png
    - assets/icons/routechange.png
    - assets/icons/pass.png
    - assets/icons/receipt.png
    - assets/icons/busstop.png.

  fonts:
    - family: FasterOne
      fonts:
        - asset: assets/fonts/FasterOne-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf
        - asset: assets/fonts/LatoBold.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
        - asset: assets/fonts/PoppinsBold.ttf